---
- hosts: localhost
  connection: local
  pre_tasks:

    - name: Install Dependencies
      package:
        name:
          - 'acl'
          - 'bzip2'
          - 'git'
          - 'make'
          - 'python3-psycopg2'
          -  'tar'
          - 'virtualenv'
          #- 'python-psutil'
          #- slurm-drmaa-dev
          - python-psutil
          - 'libbz2-dev'
          - 'liblzma-dev'

  roles:
    - { role: geerlingguy.pip, become: yes }
    - { role: galaxyproject.postgresql, become: yes }
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
    - role: galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
#    - { role: usegalaxy_eu.rabbitmq, become: yes }
    - { role: galaxyproject.gxadmin, become: yes }



