---
- hosts: 127.0.0.1

  pre_tasks:

    - name: Install Dependencies
      package:
        name:
          - 'acl'
          - 'bzip2'
          - 'git'
          - 'make'
          - 'python3-psycopg2'
          -  'tar'
          - 'virtualenv'
          - slurm-wlm
          - slurm-drmaa-dev
          - python-psutil
          - libbz2-dev
          - liblzma-dev

  roles:
    - geerlingguy.pip
    - galaxyproject.postgresql
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
    - role: galaxyproject.galaxy
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - usegalaxy_eu.rabbitmq
    - galaxyproject.gxadmin



  post_tasks:

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      when: not nginx_supervisor

