---

- hosts: tflocal
  connection: local
  vars_files:
    - environments/tflocal/group_vars/secret.yml
  pre_tasks:
    - name: Create root for galaxy user
      become: true
      become_user: root
      file:
        path: "{{ galaxy_root }}"
        state: directory
        owner: galaxy


    - name: Install Dependencies
      package:
        name:
          - 'acl'
          - 'bzip2'
          - 'git'
          - 'make'
          - 'python3-psycopg2'
          -  'tar'
          - 'virtualenv'
          #- 'python-psutil'
          #- slurm-drmaa-dev
          - python-psutil
          - 'libbz2-dev'
          - 'liblzma-dev'

  roles:
    - role: geerlingguy.pip
      become: yes
      become_user: root
    - role: galaxyproject.postgresql
      become: yes
      become_user: root
    - role: galaxyproject.postgresql_objects
      become: true
      become_user: postgres
    - role: galaxyproject.galaxy
      become: true
      become_user: "{{ galaxy_user.name }}"
    - role: uchida.miniconda
      become: true
      become_user: "{{ galaxy_user.name }}"
    - role: galaxyproject.nginx
      become: yes
      become_user: root
#    - { role: usegalaxy_eu.rabbitmq, become: yes }
    - role: galaxyproject.gxadmin
      become: yes
      become_user: root}

  post_tasks:
    - name: Copy local tools to local_tool_dir
      become: true
      become_user: root
      copy:
        src: "{{ galaxy_local_tools_src_dir }}"
        dest: "{{ galaxy_local_tools_dir }}"
        owner: "{{ galaxy_user.name }}"

